### ISSUE TITLE
PHP Error si un folder ne contient aucun flux

### ISSUE THREAD

**Issue by kvnco** [barbogogo/leed-API#11]
Bonjour,

Juste après l'identification, lors du premier chargement, à l'exécution de la requête /leed/plugins/api/json.php?option=getFolders, j'obtiens l'erreur suivante :
{"error":{"id":"3","message":"<h1>PHP Error</h1><p>Note[8]Undefined index: 1- /var/www/leedk/plugins/api/json.php(l.183)</p><p>Your server configuration:</p><ul><li>PHP Version: 5.3.3-7+squeeze14</li><li>JSON Version: 1.2.1</li><li>MySQL Version: 1.0</li></ul>"}}

Je n'obtiens pas d'erreur spécifique dans les logs sur le serveur. Avez-vous une piste pour m'aider ?

Merci !

**Comment by barbogogo** [comment]
Bonjour,

Merci pour ce retour.

Points à vérifier qui pourraient être source de ce problème :
- Est-ce que de répertoire avec l'ID = 1 est vide (sans aucun flux ni article, même lu) ?
- Est-ce qu'il existe des articles classés dans le répertoire avec l'ID = 1 sans que ce répertoire existe ?

**Comment by kvnco** [comment]
Merci pour ce premier retour !
Il va falloir que je regarde tout ça, mais je peux déjà confirmer que le
répertoire "Géneral" (créé par défaut, qui a donc fort probablement l'ID 1)
est vide chez moi.

**Comment by kvnco** [comment]
Hello,

Je confirme le bug qui survient si un folder ("Géneral" ou autre) ne contient aucun flux.

**Comment by barbogogo** [comment]
Encore merci.
Mise à jour de Leed-API : http://www.barbogogo.fr/leed-api-v0-10-est-disponible/
