### ISSUE TITLE
Salage du mot de passe dans Leed => Pas de connexion

### ISSUE THREAD

**Issue by Sbgodin** [barbogogo/leed-API#13]
Salutations,

Dans la branche dev de Leed, j'ai changé la façon dont l'authentification se fait. leedReader ne peut plus s'authentifier.

J'ai constaté dans les logs du serveur web une ligne du type :
`GET /leed/plugins/api/login.php?&login=LOGIN&password=PASSWORD`
La donnée PASSWORD étant le condensat du mot de passe tel qu'il se trouvait dans la base de données.

Dans la version de dev, le mot de passe est salé avec une donnée propre à l'installation. Le sel est régénéré en cas de changement de mot de passe. Comme au niveau de _Leed-API_, on ne reçoit que le condensat donné par LeedReader ça ne peut plus marcher.

Je suppose, sauf erreur toujours, qu'il faudrait soumettre le mot de passe lui-même à partir de LeedReader.

**Comment by barbogogo** [comment]
Salut @Sbgodin,

Merci de m'informer de cette évolution.

Le salage est par conséquent indisponible directement...
Le but de la transmission du condensat est que le mot de passe ne passe pas en clair sur le net.
LeedReader permet la connexion par digest (qui n'est pas celle par défaut). Peut être que si ce type de connexion est utilisé et qu'une modification du fichier auth.php est réalisée, alors ça peut marcher.
Comment serait-il possible de récupérer le salage à partir de l'API ? Est-ce possible ?

**Comment by Sbgodin** [comment]
Hello,

Merci pour le travail fait, j'utilise avec plaisir l'API et LeedReader. Enfin, disons que j'utilisais ; travaillant sur la version de développement, je dois nécessairement la tester, et donc ne plus pouvoir utiliser l'application.

L'utilisation du condensat tel quel est une fausse sécurité. D'abord, le mot de passe peut être trouvé par force brute, voire même en utilisant les nombreux sites qui testent la génération du condensat (SHA1 entre autres). Ensuite, ça n'empêche pas le rejeu : si j'intercepte la communication, je peux rejouer le condensat. Peu importe la clé pourvu qu'on ait l'accès ;-)

La seule vraie sécurité est la connexion chiffrée en TLS, du ressort de l'administrateur du serveur. Reste à voir la sécurité apportée par le mode _digest_, mais je crois savoir qu'il est plus facile d'avoir du TLS que du digest.

L'API ayant les mains dedans, il est tout à fait possible de récupérer le sel. Il est stocké dans la table _configuration_, variable _cryptographicSalt_. Mais, par principe, il ne doit jamais quitter le serveur. De plus, il peut être amené à changer avec le temps sans préavis.

Dans la version de développement, j'ai ajouté la cas à cocher _se souvenir de moi_. Ça repose sur l'utilisation d'un cookie contenant un jeton (dépendant pour le moment du compte et du passe). Tu peux peut-être reprendre le contenu du jeton en utilisant _User::getToken()_ ? À terme, même avec Leed en multi-utilisateur, chaque utilisateur disposera de son jeton. Maintenant il est strictement dépendant du compte et du passe mais à terme il sera aléatoire et stocké en base. Dans tous les cas, l'API pour LeedReader n'aurait pas à changer.

Voilà l'idée : utiliser le jeton fourni par _User::getToken()_ depuis LeedReader. L'API appelle User::existAuthToken() pour récupérer un objet si ça correspond. Évidemment, la première connexion doit utiliser le mot de passe.

Sinon, à défaut, il est toujours possible de diverger la branche de développement de Leed, bidouiller et de discuter ensuite.

**Comment by barbogogo** [comment]
Salut,

En effet, le TLS est peut être plus sûr, mais compliqué à mettre en place pour un novice : https://github.com/barbogogo/leedReader/issues/18.

Il est possible d'envoyer le mot de passe et de récupérer le sel via l'API pour permettre la connexion.
Est-ce que le jeton est toujours disponible, ou il faut absolument avoir la case "se souvenir de moi" de cochée ?

Toutefois, il me semble dommage de saler le mot de passe pour que celui-ci soit transmis en clair entre LeedReader et l'API. Aujourd'hui, je n'ai pas trouvé de solution simple (hormis le chiffrage du mot de passe depuis LeedReader...).

Je ne suis pas encore convaincu et je n'arrive pas à trouver une solution simple et accessible... toutefois, je reste bien entendu ouvert, car la sécurité de l'information est importante !!

**Comment by Sbgodin** [comment]
Ah oui, pour le certificat dans Android, ce n'est pas donné ^^ J'ai testé en connaisseur. Ce qui me fait encore plus penser que les certificats TLS sont de l'arnaque gentillement organisée, reposant sur la peur...

En fait, le jeton prend la forme d'une variable dans l'url pour le _bookmarklet_ et d'une valeur dans un cookie pour le _rememberMe_. L'important c'est que l'appelant connaisse la valeur de cette variable. L'API le connaît forcément déjà, vu qu'il est en base. La case cochée (et le $_POST correspondant) provoque la création du cookie qui est vérifié à chaque remontée.

J'ai bien une idée supplémentaire le problème. Une clé d'API. À l'installation ou bien à volonté, une clé d'API est générée lors du paramétrage du greffon. Cette clé, aléatoire stocké côté serveur, pourra être affichée en toutes lettres ou via un QR-code. C'est un genre de compte/passe spécifique à l'API. Évidemment, ça n'empêche pas non plus le rejeu, comme toute les autres solutions déjà exposées sauf TLS.

Sinon, on peut taper dans le lourd. Une graine est aléatoire est crée. On passe (pour simplifier) 10000 fois une fonction de hachage. Le 10000ème résultat est le mot de passe jetable. Une fois utilisé, le serveur attendra le 9999ème. Serveur comme client savent le faire, puisqu'ils disposent de la graine. Par contre, un attaquant ne pourra remonter la liste des mots de passe, vu le caractère non calculatoirement inversible du condensat. C'est une solution classique, mais je ne retrouve plus son nom de tête...

**Comment by barbogogo** [comment]
Salut,

Merci pour ces détails.

J'avais pensé à la clé d'API, mais il ne faut pas qu'elle soit transmise en clair, sinon les données deviennent directement accessibles via l'API... à voir si c'est gérable avec un _digest_ ou pas...

Pour le dernier point, je n'ai pas tout compris. Ou est passé le sel ? Quel est le lien entre la _graine_ et le _mot de passe salé_ de l'utilisateur ? Qui gère quoi entre l'application et l'API ?
Toutefois, il semblerait que ce soit intéressant, à voir si c'est si complexe et si ça prend beaucoup de ressources (côté client et coté serveur)...

**Comment by Sbgodin** [comment]
Le problème de cette clé d'API est le même que pour le condensat transmis tel quel : aucun n'empêche le rejeu. Pour le bloquer, il faut un système de défi-réponse. C'est-à-dire que le serveur demande au client de faire quelque chose que seul le client sait faire. HTTPS (via TLS) marche selon ce principe, tout comme tout le système fabriquant une séquence de clé incalculable par quelqu'un n'ayant pas la graine.

Détails académiques ici sur l'OTP : https://fr.wikipedia.org/wiki/Mot_de_passe_unique

Concrètement, côté serveur on génère une graine aléatoire. Il faut la communiquer au client une seule fois. Ensuite chacun d'eux génère une liste de, mettons, 10 mots de passes à partir de la graine. Chaque passe dépendant du précédent, le calcul inverse étant impossible. À la première connexion, le client émet le mot de passe n°10. Le serveur le reconnaît et brûle ce numéro, qui n'est plus valable. Le client devra émettre le n°9 et ainsi de suite jusqu'à expiration, où il faudra produire une nouvelle graine.

Un exemple de liste : https://gist.github.com/Sbgodin/8089778

En pratique, il faut aussi gérer la désynchronisation au niveau de la clé attendue par le serveur. Et en plus, c'est le cas via le navigateur, il suffit de rejouer le numéro de session. J'imagine qu'avec LeedReader, le programme s'authentifie à chaque connexion ?

**Comment by barbogogo** [comment]
LeedReader ne s'identifie qu'à son lancement où une session est ouverte.

Toutefois, si j'ai bien compris, lors de l'installation de l'API, il faudrait créer une _graine_ aléatoirement. Ensuite cette graine serait renseignée dans LeedReader à la place du _mot de passe_. Il faudra également renseigné le _login_ pour la gestion du multi-utilisateur. Il faudrait toutefois une graine distincte pour chacun des utilisateurs, mais pas trop longue pour une saisie manuelle.

Ensuite, un système d'OTP serait réalisé entre l'API et LeedReader. Si les deux _mots de passe_ calculés sont équivalents, tout est ok et on peut obtenir les informations (plus besoin du _login_ et du _mot de passe_ dans LeedReader).

En gros, la seule difficulté est la gestion des graines en mode multi-utilisateurs... une des solutions serait de saler la _graine_ avec le _login_ (petit écart avec ton exemple) et de prendre les x-premiers caractères pour faire la _graine_ (pour que la saisie manuelle soit plus simple).
Penses-tu que le niveau de sécurité serait suffisant ? Sachant que l'inconnue est seulement le _sel_ (on peut connaitre le _login_ et le nombre de caractères pris en compte)...

**Comment by agentcobra** [comment]
Pour la configuration de l'application utilisation d'un QRCode ?

**Comment by barbogogo** [comment]
oui, pourquoi pas...

**Comment by Sbgodin** [comment]
@barbogogo c'est l'idée. Pour le multi-utilisateur, il suffit juste de personnaliser la fonction de hachage pour chaque utilisateur. Ce sera le cas pour le stockage du mot de passe pour une connexion ordinaire. Un sel, aléatoire, défini par utilisateur. Chacun d'eux pourra se voir attribuer un jeton de connexion, qui est cette fameuse graine.

Mais bon, c'est de la bonne grosse artillerie ! Surtout que lorsque l'authentification n'est réalisé qu'à la connexion, alors on peut toujours voler l'identifiant de session si on écoute le réseau. Pour que ce système vaille le coup, il faudrait soit utiliser une clé à chaque connexion HTTP, soit pouvoir masquer la communication. Mais si on sait masquer la communication (via TLS...) alors on n'a plus besoin de l'OTP.

En pratique, selon mes sources, l'OTP sert à authentifier la première connexion qui va ensuite utiliser un réseau privé virtuel (VPN). Le _RSA SecurID_ sert à nitier les connexions VPN. Bon, là, chez RSA on est copain avec les services secrets états-uniens...

Au final, reste toujours le problème de vol de connexion par rejeu de l'identifiant de session ou du compte/passe. Sauf à ce que le mode _digest_ de HTTP me cache une surprise, hors de TLS point de salut !

**Comment by cobalt74** [comment]
hello, les gars. @barbogogo serait-il possible d'avoir une version qui fonctionne pour la v1.6 de Leed ? (même si c'est pas le top du top niveau sécurité)

j'ai vu passer un moment l'idée de prendre le jeton (code utilisé pour la synchro si j'ai bien compris)
dans l'idée, pourquoi ne pas générer un jeton spécifique pour les plugins. (ou pour ton plugin dans notre cas)
- Ton API génère ce code lors de l'installation (dans la table configuration - clé plugin-api-key)
- Tu affiches cette clé dans les settings.
- Du coup cette clé ne permet de faire que ce que tu as indiqué dans les fonctions de l'API et ne correspond pas au compte de l'utilisateur.

Quand penses-tu ?

**Comment by barbogogo** [comment]
Salut,Ok. Si j'ai bien compris, le mot de passe est salé avec le sel de leed et de mon coté, j'ai une autre clé pour mon authentification.Je regarde ça :smile:--------- Original Message ---------From: Cobalt74 To: barbogogo/leed-API Date: Mon Feb 24 17:37:40 UTC+01:00 2014Subject: Re: [leed-API] Salage du mot de passe dans Leed => Pas de connexion (#13)
hello, les gars. @barbogogo serait-il possible d'avoir une version qui fonctionne pour la v1.6 de Leed ? (même si c'est pas le top du top niveau sécurité)

j'ai vu passer un moment l'idée de prendre le jeton (code utilisé pour la synchro si j'ai bien compris)
dans l'idée, pourquoi ne pas générer un jeton spécifique pour les plugins. (ou pour ton plugin dans notre cas)

Ton API génère ce code lors de l'installation (dans la table configuration - clé plugin-api-key)
Tu affiches cette clé dans les settings.
Du coup cette clé ne permet de faire que ce que tu as indiqué dans les fonctions de l'API et ne correspond pas au compte de l'utilisateur.
Quand penses-tu ?

**Comment by barbogogo** [comment]
Salut,

Pour que ça fonctionne en mode digest, il faut que l'appli envoie le mot de passe salé.  Il faut donc le sel dans l'appli...
Ça peut finctionner si on envoie le mot de passe en clair et que l'on récupère le sel au niveau de l'API...

**Comment by cobalt74** [comment]
le sel ne devrait pas quitter la BDD :)

tu génère un code API (à l'image du code de synchro de Leed)
- ce code peut servir de mot de passe en mode digest (à traiter coté API)
- ce code peut servir de code d'identification en mode http.

**Comment by barbogogo** [comment]
Salut,Du coup en mode digest, on ne regarde pas le mot de passe... mais on a un code.Et en http, tout passe en clair...Je vais regardé plus en détails.

**Comment by cobalt74** [comment]
dans tous les cas tu as le user + le code pour t'identifier sur l'API. (en mode http ou digest)

**Comment by cobalt74** [comment]
je rajoute : Comme ça le mot de passe reste coté Leed.

**Comment by barbogogo** [comment]
Le mot de passe salé et le sel restent dans Leed.Je pense que l'API peut utiliser le sel, non?--------- Original Message ---------From: Cobalt74 To: barbogogo/leed-API Date: Thu Feb 27 13:45:38 UTC+01:00 2014Subject: Re: [leed-API] Salage du mot de passe dans Leed => Pas de connexion (#13)
je rajoute : Comme ça le mot de passe reste coté Leed.

**Comment by cobalt74** [comment]
Pour ? je m'y perd un peu :smile: 
Fait nous un exposé de ce que tu as en tête.

**Comment by barbogogo** [comment]
Je trouve domage de ne plus utiliser le login (surtout pour du multi utilisateur) et le mot de passe, en les remplaçants par un id.

Mais c'est surement moi qui m'y perds :smile:

**Comment by Sbgodin** [comment]
On peut les utiliser pour l'authentification. Et en fait, il ne faut utiliser que cela. La mécanique de salage doit rester au sein de Leed. D'autant qu'elle évoluera plus tard avec le mode multi-utilisateur.
1. L'API peut utiliser une clé unique pour l'accès vers elle, auquel cas cela vaudra connexion automatique à l'utilisateur par défaut.
2. L'API peut encore utiliser cette clé associée avec un utilisateur, mais il faudra qu'ils se fassent confiance....
3. L'API peut associer à chaque utilisateur une clé unique, que les connexions entrantes utiliseront comme mot de passe.
4. Au niveau de Leed, on peut également associer une clé d'API spécifique à chaque utilisateur qui servira en fait de mot de passe spécifique à l'API.

**Comment by barbogogo** [comment]
Merci pour ces détails. Dans un premier temps je me baserai sur la seconde solution pour tendre vers la quatrième solution si les développeurs de Leed sont ok.Toutefois, cette clé aléatoire reste sensible car avec celle-ci il est possible d'accéder aux contenus de la BDD, sans toutefois, pouvoir faire de grandes modifications (seulement le statut lu/non lu et favoris/non favori d'un article).

**Comment by cobalt74** [comment]
:+1:

**Comment by barbogogo** [comment]
Bonjour,

J'aimerai afficher la clé de l'API dans les informations de l'API (sur la page http://rss.esucom.fr/settings.php#pluginBloc). Comment est-ce possible ? Je n'ai pas trouvé de hook me permettant de réaliser cette tâche (peut être que j'ai mal chercher ou que c'est faisable via un autre moyen...).

Merci :smile:

**Comment by cobalt74** [comment]
salut @barbogogo,
en exemple, prends le plugin leedStats.

fonction `leedStats_plugin_setting_link` pour le lien dans le menu settings avec
`Plugin::addHook('setting_post_link', 'leedStats_plugin_setting_link');`

fonction `leedStats_plugin_setting_bloc` pour la partie affichage
`Plugin::addHook('setting_post_section', 'leedStats_plugin_setting_bloc');`
ton affichage doit être fais dans

``` php
<section id="leedStatslBloc" class="leedStatslBloc">
</section>
```

**Comment by barbogogo** [comment]
Bonjour à tous,

L'API v0.11 est disponible pour Leed v1.6. Merci à tous pour votre collaboration et désolé de ne pas avoir assimilé l'affaire tout de suite...

https://github.com/barbogogo/leed-API/tree/846698afa4dff45c2833142d6028c7d7c8dbef29

**Comment by cobalt74** [comment]
Cool, je test ce soir.

**Comment by Sbgodin** [comment]
J'ai mis à jour LeedReader v1.7 et l'API v0.11 (846698afa4dff45c2833142d6028c7d7c8dbef29). Ça connecte.

Après ça a planté, c'est écrit tout petit...

**Comment by barbogogo** [comment]
Salut @Sbgodin,
Merci pour ton retour. 
Est-ce que tu peux donner plus de détails ? Je viens de tout réinstaller pour re-tester et je n'ai eu aucun problème...
Voici la configuration qui fonctionne :
- Leed v1.6.1 : https://github.com/ldleman/Leed/tree/db332c1e132699f2fb2680ba5e86390b88273138
- LeedAPI v0.11 : https://github.com/barbogogo/leed-API/tree/846698afa4dff45c2833142d6028c7d7c8dbef29
- LeedReader v1.7 : http://barbogogo.fr/xplorer/data/public/4bb670.php

**Comment by Sbgodin** [comment]
Je me assuré d'avoir les bonnes versions. Voici l'affichage de mon téléphone, Galaxy S4 :
![screenshot_2014-03-05-21-43-06](https://f.cloud.github.com/assets/3691603/2338244/0320d4d6-a4a7-11e3-887c-3e24746979a2.png)

**Comment by barbogogo** [comment]
Merci pour la capture d'écran. 

Donc, ça marche,  mais c'est écrit petit.

Le problème n'est pas lié à la mise à jour de l'API.

Je regarde le problème. Et pour l'affichage des articles, c'est la même chose?

**Comment by Sbgodin** [comment]
Le titre est écrit aussi petit, mais le corps est lisible.

**Comment by cobalt74** [comment]
c'est en test ;)
clé api renseignée ! nice. 
en complément, il faudrait un bouton pour faire une génération auto de l'API dans le cas ou on souhaite la mettre à jour. (changement de la clé tous les mois pour la sécurité) :)

**Comment by barbogogo** [comment]
Salut @cobalt74,

Merci pour ton retour.

Effectivement, un bouton peut être ajouté. En attendant, une désactivation et réactivation du plugin permet de générer une nouvelle clé.

**Comment by cobalt74** [comment]
ah ok cool. j'avais pas vu. Est ce que tu mettrais pas l'api sur le market de Leed ? avec une petite description qui indique ou télécharger l'application android.

**Comment by barbogogo** [comment]
Salut @cobalt74,

Ok, je vais regarder de plus près comment mettre l'API sur le market :smile:

**Comment by barbogogo** [comment]
@cobalt74, je n'ai pas accès pour faire un `git push`...

**Comment by cobalt74** [comment]
et non :) la technique :
- tu clone le market : barbogogo/leed-market
- tu fait les modifs sur ton clone. tu commit, et tu envoi sur le site de github. (ça c'est le truc normal)
- tu fais un pullrequest vers le projet principal (depuis le site web)
- on reçoit la demande, on fait plein de commentaires :wink: 
- on commit coté leed-market après toute ces vérifications arasantes ^!^

**Comment by barbogogo** [comment]
ok, ça marche :smile: 

merci !!

**Comment by cobalt74** [comment]
j'ai pas vu de suite, mais en faite, tu as 2 répertoires api ?? (j'ai commité un peu vite)

**Comment by barbogogo** [comment]
?? c'est à dire deux répertoires API ??

C'est la structure qui ne va pas ? Il faut que je mette tous les fichiers dans `API` et non dans `API/api` ?

**Comment by cobalt74** [comment]
je l'ai fait ;) désolé. je suis allé un peu vite.

**Comment by cobalt74** [comment]
bon alors du coup je test, je test et je vois des trucs affreux affreux affreux.

leedStats_plugin_setting_link() c'est une fonction utilisée par le plugin leedStats.
il faut que tu change ces noms en api_plugin_setting_link() etc.

**Comment by cobalt74** [comment]
je l'ai fais pour corriger ;) tu as plus qu'a récupérer.

**Comment by barbogogo** [comment]
En effet, j'ai oublié de le modifier...

Merci.

**Comment by cobalt74** [comment]
yop. j'ai trouvé une incompatibilité avec un plugin et du coup j'aimerai mettre:

`require_once('constantAPI.php');`
dans api.plugin

est ce que tu peux me dire si ça génère des erreurs chez toi ?

**Comment by Sbgodin** [comment]
On peut fermer ce ticket, je pense.

**Comment by barbogogo** [comment]
Merci @Sbgodin

**Comment by Sbgodin** [comment]
@barbogogo, tu continues à suivre les développements de Leed avec LeedReader ?

**Comment by barbogogo** [comment]
Pas tellement. J'ai fait une installation complète il y a 2 mois et je n'ai pas eu de soucis. Par contre, je n'apporte plus d'amélioration ni sur l'API ni sur l'application.

**Comment by Sbgodin** [comment]
Très bien ! Je continue donc à surveiller la compatibilité avec Leed-API et LeedReader. Merci pour le boulot :smile:

**Comment by barbogogo** [comment]
Merci à toi d'être fidèle au poste !
