### ISSUE TITLE
L'identifiant et le mot de passe sont transmis en clair

### ISSUE THREAD

**Issue by gbour** [barbogogo/leed-API#5]
voici un exemple d'url :

_/leed/plugins/api/json.php?option=article&idArticle=1&login=myuser&password=mypassword_

L'identifiant et mot de passe sont transmis en clair, ce qui pose un problème de sécurité

Cdt,
Guillaume

**Comment by barbogogo** [comment]
Bonjour Guillaume,

En effet, toutes les données sont transmises en clair entre l'API et le logiciel externe.
L'issue https://github.com/barbogogo/leedReader/issues/18 que tu as ouverte pourrait résoudre le problème.

Merci,
Jérôme

**Comment by gbour** [comment]
Bonjour Jérome.

À mon sens, les deux ne sont pas exclusifs et sont nécessaire.
On peut vouloir héberger leed sur un mutualisé par exemple, où on ne pourra pas forcément activer le SSL.

Je pense qu'il doit être relativement simple de faire une auth de type digest avec php en utilisant les sessions.
Si j'ai un peut de temps, je ferais un patch

Guillaume.

**Comment by barbogogo** [comment]
Bonjour Guillaume,
Ok, je vois.
Je vais regarder comment faire une connexion http entre java et php en utilisant les sessions.
Jérôme

**Comment by barbogogo** [comment]
https://github.com/barbogogo/leedReader/pull/20

**Comment by agentcobra** [comment]
on peut utiliser la clef de synchro pour crypter en tant que salt par exemple

**Comment by barbogogo** [comment]
Bonjour @agentcobra,
Tu voudrais crypter les données (répertoire et flux RSS) échangées entre l'API et l'application LeedReader ?
Barbogogo

**Comment by agentcobra** [comment]
Oui, ça serai bien

**Comment by barbogogo** [comment]
Pourquoi pas, mais pour moi, ce n'est pas la priorité.
En effet, je ne considère pas que les données échangées soient confidentielles et qu'elles doivent être transmises chiffrées.
